In [1]:
import pandas as pd
import numpy as np

# visualization
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [3]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df_train.drop('Name', axis = 1, inplace = True)

In [7]:
df_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [8]:
df_train.drop(['Cabin','Ticket','PassengerId'], axis = 1, inplace = True)

In [9]:
df_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [10]:
df_train.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [11]:
df_train['Embarked']= df_train['Embarked'].fillna("S")

In [12]:
df_train['Sex'] = df_train['Sex'].map({'female':0,'male':1})

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(5), object(1)
memory usage: 55.8+ KB


In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [15]:
df_train['Embarked'] = labelencoder.fit_transform(df_train['Embarked'])

In [16]:
df_train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [17]:
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].mean())

In [18]:
df_train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [19]:
df_train.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [20]:
Y = df_train['Survived']
X = df_train.drop('Survived',axis = 1)

In [21]:
df_train['Family'] = df_train['SibSp']+ df_train['Parch']

In [22]:
df_train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Family
0         0       3    1  22.0      1      0   7.2500         2       1
1         1       1    0  38.0      1      0  71.2833         0       1
2         1       3    0  26.0      0      0   7.9250         2       0
3         1       1    0  35.0      1      0  53.1000         2       1
4         0       3    1  35.0      0      0   8.0500         2       0

In [23]:
df_train.drop({'SibSp','Parch'},axis = 1,inplace = True)

In [24]:
df_train.head()

Survived  Pclass  Sex   Age     Fare  Embarked  Family
0         0       3    1  22.0   7.2500         2       1
1         1       1    0  38.0  71.2833         0       1
2         1       3    0  26.0   7.9250         2       0
3         1       1    0  35.0  53.1000         2       1
4         0       3    1  35.0   8.0500         2       0

In [25]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   Fare      891 non-null    float64
 5   Embarked  891 non-null    int32  
 6   Family    891 non-null    int64  
dtypes: float64(2), int32(1), int64(4)
memory usage: 45.4 KB


In [26]:
X = df_train.iloc[:, 1:].to_numpy(dtype = "float64")
X

array([[ 3.        ,  1.        , 22.        ,  7.25      ,  2.        ,
         1.        ],
       [ 1.        ,  0.        , 38.        , 71.2833    ,  0.        ,
         1.        ],
       [ 3.        ,  0.        , 26.        ,  7.925     ,  2.        ,
         0.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, 23.45      ,  2.        ,
         3.        ],
       [ 1.        ,  1.        , 26.        , 30.        ,  0.        ,
         0.        ],
       [ 3.        ,  1.        , 32.        ,  7.75      ,  1.        ,
         0.        ]])

In [27]:
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [28]:
df_test['Family'] = df_test['SibSp']+ df_test['Parch']
df_test.drop({'SibSp','Parch'},axis = 1,inplace = True)

In [29]:
df_test.drop({'PassengerId','Name','Ticket','Cabin'},axis =1,inplace = True)

In [30]:
df_test['Sex'] = labelencoder.fit_transform(df_test['Sex'])

In [31]:
df_test['Embarked'] = labelencoder.fit_transform(df_test['Embarked'])

In [32]:
df_test.head()

Pclass  Sex   Age     Fare  Embarked  Family
0       3    1  34.5   7.8292         1       0
1       3    0  47.0   7.0000         2       1
2       2    1  62.0   9.6875         1       0
3       3    1  27.0   8.6625         2       0
4       3    0  22.0  12.2875         2       2

In [33]:
df_test['Fare'] = df_test['Fare'].fillna(df_test['Fare'].mean())

In [34]:
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].mean())

In [35]:
df_test.head()

Pclass  Sex   Age     Fare  Embarked  Family
0       3    1  34.5   7.8292         1       0
1       3    0  47.0   7.0000         2       1
2       2    1  62.0   9.6875         1       0
3       3    1  27.0   8.6625         2       0
4       3    0  22.0  12.2875         2       2

In [36]:
y = df_test.to_numpy(dtype = "float64")
y

array([[ 3.        ,  1.        , 34.5       ,  7.8292    ,  1.        ,
         0.        ],
       [ 3.        ,  0.        , 47.        ,  7.        ,  2.        ,
         1.        ],
       [ 2.        ,  1.        , 62.        ,  9.6875    ,  1.        ,
         0.        ],
       ...,
       [ 3.        ,  1.        , 38.5       ,  7.25      ,  2.        ,
         0.        ],
       [ 3.        ,  1.        , 30.27259036,  8.05      ,  2.        ,
         0.        ],
       [ 3.        ,  1.        , 30.27259036, 22.3583    ,  0.        ,
         2.        ]])

In [37]:
y_test = pd.read_csv('gender_submission.csv')
df_test

Pclass  Sex       Age      Fare  Embarked  Family
0         3    1  34.50000    7.8292         1       0
1         3    0  47.00000    7.0000         2       1
2         2    1  62.00000    9.6875         1       0
3         3    1  27.00000    8.6625         2       0
4         3    0  22.00000   12.2875         2       2
..      ...  ...       ...       ...       ...     ...
413       3    1  30.27259    8.0500         2       0
414       1    0  39.00000  108.9000         0       0
415       3    1  38.50000    7.2500         2       0
416       3    1  30.27259    8.0500         2       0
417       3    1  30.27259   22.3583         0       2

[418 rows x 6 columns]

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [39]:
y_train = Y
y_train = y_train.to_numpy(dtype = 'float64')
y_train

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0.

In [40]:
y_test = y_test.iloc[:, 1:].to_numpy(dtype = "float64")
y_test

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [41]:
X_train = X

In [42]:
X_test = y

In [45]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       0.96      0.95      0.95       266
         1.0       0.91      0.93      0.92       152

    accuracy                           0.94       418
   macro avg       0.93      0.94      0.94       418
weighted avg       0.94      0.94      0.94       418

[[252  14]
 [ 11 141]]
accuracy is 0.9401913875598086


In [46]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       0.97      0.87      0.92       266
         1.0       0.81      0.95      0.87       152

    accuracy                           0.90       418
   macro avg       0.89      0.91      0.90       418
weighted avg       0.91      0.90      0.90       418

[[231  35]
 [  7 145]]
accuracy is 0.8995215311004785
